### PR TITLE
Patch implement tests

### PR DESCRIPTION
**Pull request by buildthomas**
Add test cases for most of the implementation.

Blocked because lemur is not updated to support some of the things these test cases / the implementation needs to run in lemur.

### CODE REVIEW

**Comment by Kampfkarren** [comment]
What I do in these cases is I have a branch on my own lemur fork with everything I need to get my tests working and PR everything I think'd get merged. What exactly do you need for this to work?

**Comment by buildthomas** [comment]
> What I do in these cases is I have a branch on my own lemur fork with everything I need to get my tests working and PR everything I think'd get merged. What exactly do you need for this to work?

I think with those branches of edits you've been making it would already cover a whole bunch. Having these tests working is not a top priority for me so I don't mind waiting for lemur to get these features implemented.

**Comment by Kampfkarren** [comment]
I cover enough for it to require, I haven't gotten around to doing anything else with it, heh. I'll get around to doing unit tests with DataStore2 which means I'll make more PRs as needed.

**Comment by Kampfkarren** [comment]
The way stuff at Roblox does tests now is just by running them in Studio--`rojo build` a place file and just run TestEZ in there. It's just not possible to do it in CI, though.

**Pull request merged**
